### ISSUE TITLE
Search with comparator does not handle OperationOutcomes correctly (FI-1622)

### ISSUE THREAD

**Issue by jwjahns** [inferno-framework/us-core-test-kit#54]
Hello,

I think that comparator-based searches ( `params_with_comparators` ) do not filter out OperationOutcomes when checking if everything in the Bundle matches the provided parameters. As a result, a Bundle that has all valid results as well as a non-fatal OperationOutcome will fail due to "not matching the search parameters".

I believe the relevant code is [in search_test.rb](https://github.com/inferno-framework/us-core-test-kit/blob/4d439e11e68d2008d5b9d795d87e742d4ddd9b11/lib/us_core_test_kit/search_test.rb#L95). Non-comparator searches use the `resources_returned` array, which is filtered down to only the requested resource, but `perform_comparator_searches` does not.

Here's an example failure:
![image](https://user-images.githubusercontent.com/83475323/178077041-290d0b7c-fcc7-4696-bb5f-c93e02d22a8f.png)

The Bundle response is here: [DiagnosticReport_Bundle_json.txt](https://github.com/inferno-framework/us-core-test-kit/files/9075275/DiagnosticReport_Bundle_json.txt)
.

**Comment by yunwwang** [comment]
@jwjahns Thank you for raising this issue to us. It is a bug in our code. We will fix that.

**Comment by yunwwang** [comment]
@jwjahns I create a copy of this issue in onc-certification-g10-test-kit repo for easy tracking. The link is shown above. I will close this one as duplicate.
